# Generated by Django 3.2.5 on 2021-10-17 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(help_text='Field ini tidak boleh dikosongkan.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Field ini boleh dikosongkan.', null=True)),
                ('demo_link', models.CharField(blank=True, help_text='Field ini boleh dikosongkan.', max_length=2000, null=True)),
                ('source_link', models.CharField(blank=True, help_text='Field ini boleh dikosongkan.', max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Bisa dimodifikasi bila diperlukan.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Tidam bisa diedit.', primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
